# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  # Schedule updates every hour
  schedule:
    - cron: "0 * * * *"
  # Manual run and on push to main/master
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # General settings
          user: turtle-key
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Bucharest

          ##################################
          # Plugins for rich contributions #
          ##################################

          # Achievements
          #plugin_achievements: yes
          #plugin_achievements_display: compact
          #plugin_achievements_threshold: C
          #plugin_achievements_secrets: yes
          #plugin_achievements_ignored: explorer

          # Languages
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_colors: github
          plugin_languages_categories: markup, programming
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 10

          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Repositories traffic (views and clones)
          plugin_traffic: yes

          # Code size
          plugin_code: yes

          # Discussions
          plugin_discussions: yes

          # Topics
          #plugin_topics: yes
          #plugin_topics_mode: icons
          #plugin_topics_limit: 15

          # Notable contributions to other repositories
          plugin_contributors: yes

          # Repositories
          plugin_repositories: yes
          plugin_repositories_featured: turtle-key/TabLift

          # Stars
          plugin_stars: yes
          plugin_stars_limit: 4

          # Recent activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300
